name: Run RDW Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        # This step checks out the code from the repository to the runner.

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'
        # This step sets up Node.js version 21 on the runner.

      - name: Install Newman and HTML Reporter
        run: npm install -g newman newman-reporter-html
        # This step installs Newman and the HTML reporter globally using npm.

      - name: Run Postman Collection and generate HTML report
        id: run_postman
        run: |
          mkdir -p rdw-test-results
          TIMESTAMP=$(date +"%Y%m%d%H%M%S")
          REPORT_PATH="rdw-test-results/${TIMESTAMP}_report.html"
          newman run tests/rdw-test-collection.postman_collection.json -r html --reporter-html-export "${REPORT_PATH}"
          echo "::set-output name=report_path::${REPORT_PATH}"
        # This step runs the Postman collection using Newman and generates an HTML report, saving it to the rdw-test-results directory.

      - name: Fetch all branches
        run: git fetch --all
        # This step fetches all branches from the remote repository.

      - name: Switch to test-results branch
        run: git checkout test-results
        # This step switches to the test-results branch.

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
        # This step configures Git with a user email and name to identify the commit.

      - name: Push HTML report to test-results branch
        run: |
          git add "${{ steps.run_postman.outputs.report_path }}"
          git commit -m "Add Newman HTML report"
          git push origin test-results
        # This step adds the HTML report to the Git staging area, commits the changes with a message, and pushes the commit to the test-results branch.